
# Find and Replace the following in order to configure this file.
# IMPORTANT: Do not include leading or trailing slash!

# LOGDIR  --the directory where you want the 'deploy.log' file located (e.g. 'home/rcpts')
# SOURCE  --the location of the repo root (and this file) (e.g. 'home/rcpts/repositories/rcpts')
# DEST    --the destination for the root of this repo (e.g. 'home/rcpts/public_html/modules/rcpts')

---
deployment:
  tasks:

    # Added comment for git happiness
    - /bin/echo "==== DEPLOY START $(date) ====" >> /home/blangblo/repositories/deploy.log

    # Ensure targets exist
    - /bin/mkdir -p /home/blangblo/pmpm/modules/scan_text

    # Mirror module from repo → live (deletes removed files)
    - /bin/rsync -av --delete --exclude=.git/ --exclude=.github/ --exclude=.vscode/ --exclude=~bin/ --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r /home/blangblo/repositories/scan_text/ /home/blangblo/pmpm/modules/scan_text/ >> /home/blangblo/repositories/deploy.log 2>&1 || /bin/echo "RSYNC_MOD_FAIL code=$?" >> /home/blangblo/repositories/deploy.log

    # End marker with SHA
    - /bin/echo "==== DEPLOY END $(date)  SHA-> $(/usr/bin/git -C /home/blangblo/repositories/scan_text rev-parse --short HEAD) ====" >> /home/blangblo/repositories/deploy.log
